FROM php:8.3-cli

RUN apt-get update && apt-get install -y \
    git unzip libzip-dev \
    && docker-php-ext-install zip pcntl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY ./src .

RUN touch /app/database/database.sqlite

RUN composer install --no-dev --optimize-autoloader \
 && php artisan cache:table \
 && php artisan migrate --force

CMD ["php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8080"]