services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: beeFit
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
      - "5173:5173" # Vite
    depends_on:
      - mysql
      - redis

  reverb:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: beeFit-reverb
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: beeFit_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: beeFit_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: