<?php

namespace App\Console\Commands;

use App\Models\Equipment;
use App\Models\Exercise;
use App\Models\Muscle;
use Illuminate\Console\Command;

class ExportExerciseSeeder extends Command
{
    protected $signature = 'exercises:export-seeder
                            {--output=database/seeders/ExercisesSeeder.php : Output file path relative to base_path()}';

    protected $description = 'Export current exercises, muscles and equipment to a seeder file';

    public function handle(): int
    {
        $this->info('Loading data...');

        $muscles    = Muscle::with('translations')->get();
        $equipment  = Equipment::with('translations')->get();
        $exercises  = Exercise::with('translations')->where('is_custom', false)->get();

        $this->info("  {$muscles->count()} muscles, {$equipment->count()} equipment, {$exercises->count()} exercises");

        $musclesCode    = $this->buildMusclesArray($muscles);
        $equipmentCode  = $this->buildEquipmentArray($equipment);
        $exercisesCode  = $this->buildExercisesArray($exercises, $muscles, $equipment);

        $stub = $this->buildStub($musclesCode, $equipmentCode, $exercisesCode);

        $outputPath = base_path($this->option('output'));
        file_put_contents($outputPath, $stub);

        $this->info("Seeder written to: {$outputPath}");
        $this->info('Run it with: php artisan db:seed --class=ExercisesSeeder');

        return self::SUCCESS;
    }

    private function buildMusclesArray($muscles): string
    {
        $lines = [];
        foreach ($muscles as $m) {
            $trans = [];
            foreach ($m->translations as $t) {
                $trans[] = sprintf("['locale'=>'%s','name'=>%s]", $t->locale, $this->esc($t->name));
            }
            $lines[] = '[' . implode(',', $trans) . ']';
        }
        return "[\n            " . implode(",\n            ", $lines) . "\n        ]";
    }

    private function buildEquipmentArray($equipment): string
    {
        $lines = [];
        foreach ($equipment as $e) {
            $trans = [];
            foreach ($e->translations as $t) {
                $trans[] = sprintf("['locale'=>'%s','name'=>%s]", $t->locale, $this->esc($t->name));
            }
            $lines[] = '[' . implode(',', $trans) . ']';
        }
        return "[\n            " . implode(",\n            ", $lines) . "\n        ]";
    }

    private function buildExercisesArray($exercises, $muscles, $equipment): string
    {
        // Build lookup maps: id → index in seeder array (0-based)
        $muscleIndex    = $muscles->values()->mapWithKeys(fn($m, $i) => [$m->id => $i])->toArray();
        $equipmentIndex = $equipment->values()->mapWithKeys(fn($e, $i) => [$e->id => $i])->toArray();

        $lines = [];
        foreach ($exercises as $ex) {
            $mIdx = $muscleIndex[$ex->primary_muscle_id] ?? 0;
            $eIdx = $equipmentIndex[$ex->equipment_id]   ?? 0;

            $trans = [];
            foreach ($ex->translations as $t) {
                $trans[] = sprintf(
                    "['locale'=>'%s','name'=>%s,'description'=>%s]",
                    $t->locale,
                    $this->esc($t->name),
                    $t->description ? $this->esc($t->description) : 'null'
                );
            }

            $lines[] = sprintf(
                "['muscle'=>%d,'equipment'=>%d,'type'=>%s,'video'=>%s,'thumbnail'=>%s,'translations'=>[%s]]",
                $mIdx,
                $eIdx,
                $this->esc($ex->exercise_type ?? 'strength'),
                $ex->video_path       ? $this->esc($ex->video_path)       : 'null',
                $ex->thumbnail_path   ? $this->esc($ex->thumbnail_path)   : 'null',
                implode(',', $trans)
            );
        }

        return "[\n            " . implode(",\n            ", $lines) . "\n        ]";
    }

    private function esc(string $value): string
    {
        return "'" . addslashes($value) . "'";
    }

    private function buildStub(string $musclesCode, string $equipmentCode, string $exercisesCode): string
    {
        $date = now()->format('Y-m-d H:i:s');

        return <<<PHP
<?php

// Auto-generated by exercises:export-seeder on {$date}
// Run with: php artisan db:seed --class=ExercisesSeeder

namespace Database\Seeders;

use App\Models\Equipment;
use App\Models\EquipmentTranslation;
use App\Models\Exercise;
use App\Models\ExerciseTranslation;
use App\Models\Muscle;
use App\Models\MuscleTranslation;
use Illuminate\Database\Seeder;

class ExercisesSeeder extends Seeder
{
    public function run(): void
    {
        \$muscles   = {$musclesCode};
        \$equipment = {$equipmentCode};
        \$exercises = {$exercisesCode};

        // ── Muscles ──────────────────────────────────────────────────────────
        \$muscleIds = [];
        foreach (\$muscles as \$m) {
            \$enName = collect(\$m)->firstWhere('locale', 'en')['name'];
            \$existing = MuscleTranslation::where('locale', 'en')->where('name', \$enName)->first();
            if (\$existing) {
                \$muscleIds[] = \$existing->muscle_id;
                continue;
            }
            \$muscle = Muscle::create([]);
            \$rows = [];
            foreach (\$m as \$t) {
                \$rows[] = ['muscle_id' => \$muscle->id, 'locale' => \$t['locale'], 'name' => \$t['name'], 'created_at' => now(), 'updated_at' => now()];
            }
            MuscleTranslation::insert(\$rows);
            \$muscleIds[] = \$muscle->id;
        }

        // ── Equipment ─────────────────────────────────────────────────────────
        \$equipmentIds = [];
        foreach (\$equipment as \$e) {
            \$enName = collect(\$e)->firstWhere('locale', 'en')['name'];
            \$existing = EquipmentTranslation::where('locale', 'en')->where('name', \$enName)->first();
            if (\$existing) {
                \$equipmentIds[] = \$existing->equipment_id;
                continue;
            }
            \$eq = Equipment::create([]);
            \$rows = [];
            foreach (\$e as \$t) {
                \$rows[] = ['equipment_id' => \$eq->id, 'locale' => \$t['locale'], 'name' => \$t['name'], 'created_at' => now(), 'updated_at' => now()];
            }
            EquipmentTranslation::insert(\$rows);
            \$equipmentIds[] = \$eq->id;
        }

        // ── Exercises ─────────────────────────────────────────────────────────
        foreach (\$exercises as \$ex) {
            \$enName = collect(\$ex['translations'])->firstWhere('locale', 'en')['name'];
            if (ExerciseTranslation::where('locale', 'en')->where('name', \$enName)->exists()) {
                continue;
            }

            \$exercise = Exercise::create([
                'primary_muscle_id' => \$muscleIds[\$ex['muscle']],
                'equipment_id'      => \$equipmentIds[\$ex['equipment']],
                'exercise_type'     => \$ex['type'],
                'video_path'        => \$ex['video'],
                'thumbnail_path'    => \$ex['thumbnail'],
                'is_custom'         => false,
            ]);

            \$rows = [];
            foreach (\$ex['translations'] as \$t) {
                \$rows[] = [
                    'exercise_id' => \$exercise->id,
                    'locale'      => \$t['locale'],
                    'name'        => \$t['name'],
                    'description' => \$t['description'] ?? null,
                    'created_at'  => now(),
                    'updated_at'  => now(),
                ];
            }
            ExerciseTranslation::insert(\$rows);
        }
    }
}
PHP;
    }
}
